"""GUI tool: convert any image into a 128x64 SSD1306 uint8_t[1024] C bitmap.

Buffer layout matches firmware/stm32/lib/display/ssd1306/ssd1306.c:
page-major, each byte = one 8-pixel-tall column, bit0 (LSB) = top pixel
of that page. See SSD1306_DrawPixel: index = x + (y/8)*width, bit = y % 8.
"""

import tkinter as tk
from tkinter import filedialog, messagebox, ttk

from PIL import Image, ImageOps, ImageTk

WIDTH, HEIGHT = 128, 64
BUFFER_SIZE = WIDTH * HEIGHT // 8
PREVIEW_SCALE = 4


def image_to_ssd1306_buffer(img_1bit: Image.Image) -> list[int]:
    pixels = img_1bit.load()
    buffer = [0] * BUFFER_SIZE
    for y in range(HEIGHT):
        for x in range(WIDTH):
            if pixels[x, y]:
                page = y // 8
                bit = y % 8
                buffer[x + page * WIDTH] |= 1 << bit
    return buffer


def buffer_to_c_array(buffer: list[int], var_name: str = "bitmap") -> str:
    lines = [
        "/* Auto-generated by tools/oled_bitmap_converter.py -- 128x64, page-major,",
        " * each byte = 1 vertical 8-pixel column, bit0 = top pixel of the page. */",
        f"const uint8_t {var_name}[{BUFFER_SIZE}] = {{",
    ]
    for i in range(0, BUFFER_SIZE, 12):
        chunk = buffer[i : i + 12]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("SSD1306 Bitmap Converter")
        self.resizable(False, False)

        self.source_image: Image.Image | None = None
        self.processed_1bit: Image.Image | None = None

        self.threshold = tk.IntVar(value=128)
        self.dither = tk.BooleanVar(value=False)
        self.invert = tk.BooleanVar(value=False)

        self._build_ui()

    def _build_ui(self):
        top = ttk.Frame(self, padding=8)
        top.grid(row=0, column=0, sticky="ew")
        ttk.Button(top, text="Open Image...", command=self.open_image).pack(side="left")

        previews = ttk.Frame(self, padding=8)
        previews.grid(row=1, column=0, sticky="ew")

        orig_frame = ttk.LabelFrame(previews, text="Original", padding=4)
        orig_frame.pack(side="left", padx=(0, 8))
        self.orig_label = ttk.Label(orig_frame)
        self.orig_label.pack()

        proc_frame = ttk.LabelFrame(previews, text=f"{WIDTH}x{HEIGHT} preview", padding=4)
        proc_frame.pack(side="left")
        self.proc_label = ttk.Label(proc_frame)
        self.proc_label.pack()

        controls = ttk.Frame(self, padding=8)
        controls.grid(row=2, column=0, sticky="ew")

        ttk.Label(controls, text="Threshold").grid(row=0, column=0, sticky="w")
        threshold_scale = ttk.Scale(
            controls, from_=0, to=255, variable=self.threshold,
            orient="horizontal", command=lambda _v: self.update_preview(),
        )
        threshold_scale.grid(row=0, column=1, sticky="ew", padx=8)
        self.threshold_value_label = ttk.Label(controls, text="128")
        self.threshold_value_label.grid(row=0, column=2, sticky="w")
        controls.columnconfigure(1, weight=1)

        ttk.Checkbutton(
            controls, text="Dithering (Floyd-Steinberg)", variable=self.dither,
            command=self.update_preview,
        ).grid(row=1, column=0, columnspan=3, sticky="w", pady=(4, 0))

        ttk.Checkbutton(
            controls, text="Invert", variable=self.invert, command=self.update_preview,
        ).grid(row=2, column=0, columnspan=3, sticky="w")

        output_frame = ttk.LabelFrame(self, text="C array output", padding=8)
        output_frame.grid(row=3, column=0, sticky="ew", padx=8, pady=8)

        self.output_text = tk.Text(output_frame, width=70, height=14, font=("Consolas", 9))
        self.output_text.pack(fill="both", expand=True)
        self.output_text.configure(state="disabled")

        btn_frame = ttk.Frame(output_frame)
        btn_frame.pack(fill="x", pady=(8, 0))
        ttk.Button(btn_frame, text="Copy to Clipboard", command=self.copy_output).pack(side="left")
        ttk.Button(btn_frame, text="Save as .h...", command=self.save_output).pack(side="left", padx=8)

    def open_image(self):
        path = filedialog.askopenfilename(
            title="Open image",
            filetypes=[("Images", "*.png *.jpg *.jpeg *.bmp *.gif *.webp"), ("All files", "*.*")],
        )
        if not path:
            return
        try:
            self.source_image = Image.open(path).convert("L")
        except Exception as exc:
            messagebox.showerror("Error", f"Could not open image:\n{exc}")
            return

        thumb = self.source_image.copy()
        thumb.thumbnail((200, 200))
        self.orig_photo = ImageTk.PhotoImage(thumb)
        self.orig_label.configure(image=self.orig_photo)

        self.update_preview()

    def update_preview(self):
        self.threshold_value_label.configure(text=str(self.threshold.get()))
        if self.source_image is None:
            return

        img = self.source_image.resize((WIDTH, HEIGHT), Image.LANCZOS)

        if self.invert.get():
            img = ImageOps.invert(img)

        if self.dither.get():
            img_1bit = img.convert("1")
        else:
            t = self.threshold.get()
            img_1bit = img.point(lambda p: 255 if p >= t else 0).convert("1", dither=Image.NONE)

        self.processed_1bit = img_1bit

        preview_img = img_1bit.resize(
            (WIDTH * PREVIEW_SCALE, HEIGHT * PREVIEW_SCALE), Image.NEAREST
        )
        self.proc_photo = ImageTk.PhotoImage(preview_img)
        self.proc_label.configure(image=self.proc_photo)

        self.regenerate_output()

    def regenerate_output(self):
        if self.processed_1bit is None:
            return
        buffer = image_to_ssd1306_buffer(self.processed_1bit)
        code = buffer_to_c_array(buffer)
        self.output_text.configure(state="normal")
        self.output_text.delete("1.0", "end")
        self.output_text.insert("1.0", code)
        self.output_text.configure(state="disabled")

    def copy_output(self):
        code = self.output_text.get("1.0", "end").strip()
        if not code:
            return
        self.clipboard_clear()
        self.clipboard_append(code)

    def save_output(self):
        code = self.output_text.get("1.0", "end").strip()
        if not code:
            messagebox.showwarning("No data", "Load an image first.")
            return
        path = filedialog.asksaveasfilename(
            title="Save as .h",
            defaultextension=".h",
            filetypes=[("Header file", "*.h"), ("All files", "*.*")],
        )
        if not path:
            return
        guard = "BITMAP_H"
        content = f"#ifndef {guard}\n#define {guard}\n\n#include <stdint.h>\n\n{code}\n\n#endif /* {guard} */\n"
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)


if __name__ == "__main__":
    App().mainloop()
